#!/bin/bash -l
#PBS -l walltime=96:00:00,nodes=1:ppn=24
#PBS -j oe
#PBS -m abe
#PBS -M will5448@umn.edu
#PBS -q small
#PBS -N resize
#PBS -o ${HOME}/job_resize_output.log
#PBS -e ${HOME}/job_resize_error.log


cd $PBS_O_WORKDIR

#module load anaconda/1.7.0
module load python2

python2 resize.py

#python linear_regression.py >& linear_regression.out

#python mnist_softmax.py >& softmax.out

#python mnist_deep_net.py >& deep_net.out
