#!/bin/bash -l
#PBS -l walltime=00:00:30,nodes=1:ppn=1,pmem=500mb
#PBS -j oe
#PBS -m abe
#PBS -M will5448@umn.edu
#PBS -q lab
#PBS -N test_arguments
#PBS -o ${HOME}/job_ml_output_`date +%Y%m%d%H%M`.log
#PBS -e ${HOME}/job_ml_error_`date +%Y%m%d%H%M`.log

# Parameters
TIMESTAMP=`date +%Y%m%d%H%M`
DATE=`date +%Y%m%d`
ID=run_${DATE}
SITE=SER
SEASON=SER_S11
ROOT=/home/packerc/shared/machine_learning/
CODE=${ROOT}code/deep_learning_for_camera_trap_images/phase1
LOG_DIR=${ROOT}data/models/${SITE}/empty_or_not/phase1/
PREDICTIONS=${ROOT}data/predictions/empty_or_not/${SITE}/${SEASON}/predictions_${ID}.json
IMAGES_ROOT=/home/packerc/shared/albums/${SITE}/
DATA_INFO=${ROOT}data/info_files/${SITE}/${SEASON}_empty.csv

# Log Parameters
echo "TIMESTAMP: $TIMESTAMP"
echo "DATE: $DATE"
echo "ID: $ID"
echo "SITE: $SITE"
echo "SEASON: $SEASON"
echo "ROOT: $ROOT"
echo "CODE: $CODE"
echo "LOG_DIR: $LOG_DIR"
echo "PREDICTIONS: $PREDICTIONS"
echo "IMAGES_ROOT: $IMAGES_ROOT"
echo "DATA_INFO: $DATA_INFO"

# Load Python
module load python3

# Execute code
cd $CODE

python print_args.py --log_dir $LOG_DIR \
--save_predictions $PREDICTIONS \
--architecture vgg \
--data_info $DATA_INFO \
--path_prefix $IMAGES_ROOT
