#!/bin/bash -l
#PBS -l walltime=120:00:00,nodes=1:ppn=4
#PBS -j oe
#PBS -q lab-long
#PBS -N upload_manifest
#PBS -o ${HOME}/upload_manifest_${PBS_JOBID}.log
#PBS -e ${HOME}/upload_manifest_error_${PBS_JOBID}.log

module load python3

cd $HOME/snapshot_safari_misc

python3 -m zooniverse_uploads.upload_manifest \
--manifest /home/packerc/shared/zooniverse/Manifests/RUA/RUA_S1__batch_0__manifest.json \
--project_id 5155 \
--password_file ~/keys/passwords.ini