#!/bin/bash -l
#PBS -l walltime=24:00:00,nodes=1:ppn=24
#PBS -j oe
#PBS -q small
#PBS -N compressing_images
#PBS -o ${HOME}/compress_images_${PBS_JOBID}.log
#PBS -e ${HOME}/compress_images_error_${PBS_JOBID}.log

cd /home/packerc/shared/scripts/snapshot_safari_misc

module load python3

python3 -m image_compression.compress_images \
-cleaned_captures_csv /home/packerc/shared/season_captures/RUA/cleaned/RUA_S1_cleaned.csv \
-output_image_dir  /home/packerc/shared/zooniverse/ToUpload/RUA_will5448/RUA_S1_Compressed \
-root_image_path /home/packerc/shared/albums/RUA/
