#!/bin/bash -l
#PBS -l walltime=24:00:00,nodes=1:ppn=24
#PBS -j oe
#PBS -q small
#PBS -N compressing_images
#PBS -o ${HOME}/compress_images.log
#PBS -e ${HOME}/compress_images_error.log

cd /home/packerc/shared/scripts

module load python2

python2 compress_images_multiprocess_v1_qsub.py \
-cleaned_captures_csv /home/packerc/shared/season_captures/SER/cleaned/SER_S11_cleaned_V3.csv \
-root_image_path /home/packerc/shared/albums/SER/SER_S11
